name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
      #run: flutter test
    - name: Build Android
      run: flutter build apk
    - name: Build IOS
      run: flutter build ios
    - name: Build Web
      run: flutter build web
