name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '1.9.1+hotfix.6'
    - name: Install dependencies
      run: flutter pub get
      #run: flutter test
    - name: Build Android
      run: flutter build apk
    - name: Build IOS
      run: flutter build ios
    - name: Build Web
      run: flutter build web
