name: Flutter Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  flutter_version: "1.12.13+hotfix.5"
  java_version: "12.x"

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Install dependencies
      run: flutter pub get
    - name: Upgrade dependencies
      run : flutter upgrade --force
      #run: flutter test
    - name: Build Android
      run: flutter build apk
    #- name: Build IOS
    #  run: flutter build ios
    - name: Build Web
      run: flutter build web
